# Generated by Django 5.2.7 on 2025-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_alter_inscripcion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='fecha_inscripcion',
            new_name='inscription_date',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
